export const PLAYER_CONNECTED = 'PLAYER_CONNECTED';
export const PLAYER_JOINED = 'PLAYER_JOINED';
export const PLAYER_MOVED = 'PLAYER_MOVED';
export const RESTART_REQUESTED = 'RESTART_REQUESTED';
export const RESTART_GAME = 'RESTART_GAME';
export const REQUEST_GAME_RESTART = 'REQUEST_GAME_RESTART';
